### ISSUE TITLE
OM->pMML of combinat1.ocd

### ISSUE THREAD

**Issue by lars-hellstrom** [OpenMath/OpenMath.github.io#36] opened 2017-07-26 10:01 UTC
The pMML rendering of the FMP of the combinat1.Stirling2 symbol is mathematically wrong, in a way that probably affects the rendering of many other formulae: 
the factor $(-1)^{m-k}$ is rendered as $-1^{(m-k)}$.
* That the base -1 needs to be fenced is a very basic rendering issue! This **must** be done correctly if you want to be taken seriously.
* The fencing of the exponent is conversely superfluous. While not wrong, it could be a sign of some bug in the conversion process.

**Comment by davidcarlisle** [comment] 2017-07-27 15:23
this is now fixed, although the math rendering of Stirling1 is clipped at the right margin due to issue #37

https://openmath.github.io//cd/combinat1.html#Stirling2

The  brackets in the exponent are by design I think (as far as I can tell what my former self thought while writing that code last century)

**Closed by davidcarlisle** 2017-07-27 15:23 UTC
